FROM almalinux
#CMD ["ping","-c5","google.com"]
#ENTRYPOINT ["ping","-c5","google.com"]
#ping -c5 google.com ping c2 apple.com -- if we override entrypoint with a command, that command is appended to the first command.
# for best practices we use CMD and ENTRYPOINT in combination.
CMD ["google.com"]
ENTRYPOINT ["ping","-c5"]